# Generated by Django 2.1.3 on 2018-11-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='publish_date',
            new_name='due_date',
        ),
    ]
