# Generated by Django 2.1.3 on 2018-11-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_auto_20181128_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
