# Generated by Django 2.1.3 on 2018-11-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181121_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Grader', 'Grader'), ('Teacher', 'Teacher')], default='Student', max_length=10),
        ),
    ]
