# Generated by Django 2.1.3 on 2018-11-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181124_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='multifactor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reader_mode',
            field=models.BooleanField(default=False),
        ),
    ]
