# Generated by Django 2.1 on 2018-11-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181112_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='courses.Course'),
        ),
    ]
