# Generated by Django 2.1 on 2018-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0009_remove_customuser_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
