# Generated by Django 2.1 on 2018-11-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher')], default='ST', max_length=10),
        ),
    ]
