# Generated by Django 2.1 on 2018-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20181117_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Grader', 'Grader'), ('Teacher', 'Teacher')], default='ST', max_length=10),
        ),
    ]
