# Generated by Django 2.1 on 2018-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_customuser_isteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.Course'),
        ),
    ]
