# Generated by Django 2.1 on 2018-11-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20181117_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
    ]
