# Generated by Django 2.1.3 on 2018-12-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('Art', 'Art'), ('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('History', 'History'), ('Literature', 'Literature'), ('Math', 'Math'), ('Music', 'Music'), ('Physics', 'Physics'), ('Political Science', 'Political Science')], default='Art', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_tools', to='courses.Course')),
            ],
        ),
    ]
