# Generated by Django 2.1.3 on 2018-12-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_tools'),
        ('tools', '0002_remove_tool_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_tools', to='courses.Course'),
        ),
    ]
