# Generated by Django 2.1 on 2018-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('a_courses', models.ManyToManyField(related_name='a_courses', to='courses.Course')),
            ],
        ),
    ]
