# Generated by Django 2.1.3 on 2018-11-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
