# Generated by Django 2.1.3 on 2018-11-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='aid',
        ),
    ]
