# Generated by Django 2.1.3 on 2018-11-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
