# Generated by Django 2.1.3 on 2018-11-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20181124_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. ENPM613', max_length=7, unique=True)),
                ('title', models.CharField(help_text='e.g. Software Design and Implementation', max_length=200)),
                ('domain', models.CharField(choices=[('Art', 'Art'), ('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('History', 'History'), ('Literature', 'Literature'), ('Math', 'Math'), ('Music', 'Music'), ('Physics', 'Physics'), ('Political Science', 'Political Science')], default='Art', max_length=30)),
                ('graders', models.ManyToManyField(blank=True, limit_choices_to={'status': 'Grader'}, related_name='course_graders', to='accounts.CustomUser')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'status': 'Student'}, related_name='course_students', to='accounts.CustomUser')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'status': 'Teacher'}, related_name='course_teachers', to='accounts.CustomUser')),
            ],
        ),
    ]
