# Generated by Django 2.1 on 2018-11-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
    ]
