# Generated by Django 2.1 on 2018-11-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='empty', max_length=200),
            preserve_default=False,
        ),
    ]
