# Generated by Django 2.1.3 on 2018-12-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_tool_course'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='course_tools', to='tools.Tool'),
        ),
    ]
