# Generated by Django 2.1.3 on 2018-11-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0004_remove_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(limit_choices_to={'uid': 1920}, to='accounts.CustomUser'),
        ),
    ]
