# Generated by Django 2.1.3 on 2018-11-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0007_auto_20181119_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='people',
        ),
        migrations.AddField(
            model_name='course',
            name='grader',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Grader'}, related_name='course_grader', to='accounts.CustomUser'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Student'}, related_name='course_students', to='accounts.CustomUser'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Teacher'}, related_name='course_teacher', to='accounts.CustomUser'),
        ),
    ]
