# Generated by Django 2.1.3 on 2018-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20181120_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
