# Generated by Django 2.1.3 on 2018-11-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20181121_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=7),
        ),
    ]
