# Generated by Django 2.1.3 on 2018-11-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181121_0848'),
        ('courses', '0013_auto_20181123_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='graders',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Grader'}, related_name='course_graders', to='accounts.CustomUser'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Teacher'}, related_name='course_teachers', to='accounts.CustomUser'),
        ),
    ]
