# Generated by Django 2.1.3 on 2018-11-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20181123_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cid',
        ),
        migrations.AlterField(
            model_name='course',
            name='domain',
            field=models.CharField(choices=[('Art', 'Art'), ('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('History', 'History'), ('Literature', 'Literature'), ('Math', 'Math'), ('Music', 'Music'), ('Physics', 'Physics'), ('Political Science', 'Political Science')], default='Art', max_length=10),
        ),
    ]
