# Generated by Django 2.1.3 on 2018-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20181124_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='e.g. ENPM613', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='e.g. Software Design and Implementation', max_length=200),
        ),
    ]
